[chesscomNews]
title = "Chess.com AktualnoÅ›ci"
url = "https://www.chess.com/pl/news"
entrySelector = "article.post-preview-component"
titleSelector = "h2 > a.post-preview-title"
linkSelector = "a.post-preview-title"
dateSelector = "time"
dateFormat = "yyyy-MM-dd HH:mm"
dateAttribute = "datetime"

[certPolska]
title = "CERT POLSKA"
url = "https://cert.pl/"
entrySelector = "li.grid-x"
titleSelector = "a.post-outer-container > h4"
linkSelector = "a.post-outer-container"
dateSelector = "div.top > span:first-child"
dateFormat = "dd MMMM yyyy"
dateAttribute = "datetime"
