[chesscomNews]
title = "Chess.com AktualnoÅ›ci"
url = "https://www.chess.com/pl/news"
entrySelector = "article.post-preview-component"
titleSelector = "h2 > a.post-preview-title"
linkSelector = "a.post-preview-title"
dateSelector = "time"
dateFormat = "yyyy-MM-dd HH:mm"
dateAttribute = "datetime"
