[chesscomNews]
title = "Chess.com Aktualności"
url = "https://www.chess.com/pl/news"
entrySelector = "article.post-preview-component"
titleSelector = "h2 > a.post-preview-title"
linkSelector = "a.post-preview-title"
dateSelector = "time"
dateFormat = "yyyy-MM-dd HH:mm"
dateAttribute = "datetime"

[certPolska]
title = "CERT POLSKA"
url = "https://cert.pl/"
entrySelector = "li.grid-x"
titleSelector = "a.post-outer-container > h4"
linkSelector = "a.post-outer-container"
dateSelector = "div.top > span:first-child"
dateFormat = "dd MMMM yyyy"

[oazapl]
title = "OAZA PL - aktualności"
url = "https://www.oaza.pl/aktualnosci/"
entrySelector = "div.latest-featured-post-small"
titleSelector = "h3.entry-title > a"
linkSelector = "h3.entry-title > a"

[katowiceOaza]
title = "Katowice Oaza"
url = "https://katowiceoaza.pl/"
entrySelector = "li.wp-block-post"
titleSelector = "h2.wp-block-post-title > a"
linkSelector = "h2.wp-block-post-title > a"
dateSelector = "div.wp-block-post-date time"
dateFormat = "yyyy-MM-dd'T'HH:mm:ssXXX"

[archidiecezja]
title = "Archidiecezja Katowicka"
url = "https://archidiecezjakatowicka.pl/"
entrySelector = "div.nspArt.nspCol2 > div"
titleSelector = "h4.nspHeader > a"
linkSelector = "h4.nspHeader > a"
dateSelector = "p.nspInfo1"
dateFormat = "dd-MM-yyyy"

[centrumXP]
title = "CentrumXP"
url = "https://www.centrumxp.pl/aktualnosci/"
entrySelector = "a.portal-entry-card"
titleSelector = "h3.wpPFxnOUGc"
linkSelector = "a.portal-entry-card"
dateSelector = "div.jxnowhmyOZ > p:nth-child(2)"
dateFormat = "dd.MM.yyyy, HH:mm"

[dobreProgramy]
title = "Dobreprogramy"
url = "https://www.dobreprogramy.pl/"
entrySelector = "div.ILap"
titleSelector = "h2.ILr3 > a"
linkSelector = "h2.ILr3 > a"
dateSelector = "div.ILy5 > time"
dateFormat = "yyyy-MM-dd'T'HH:mm:ss.SSSX"

[wladcysieci]
title = "Władcy sieci"
url = "https://wladcysieci.pl/"
entrySelector = "article.article-post"
titleSelector = "h2.post-title > a"
linkSelector = "h2.post-title > a"
dateSelector = "time.entry-date.published"
dateFormat = "yyyy-MM-dd'T'HH:mm:ssXXX"

[dziejesiewzabrzu]
title = "Dzieje się w Zabrzu"
url = "https://wladcysieci.pl/"
entrySelector = "div[data-ad-rendering-role='storymessage']"
titleSelector = "div.x1yx25j4"
linkSelector = "a[href*='/posts/']"
dateSelector = "span[data-testid='post_timestamp']"
dateFormat = "yyyy-MM-dd'T'HH:mm:ssXXX"
